### ISSUE TITLE
Forked projet to help...

### ISSUE THREAD

**Issue by fredericopissarra** [CoolerVoid/OctopusWAF#1]
This is not a real ISSUE, just telling you I found this project interesting and I've forked it.
Seen some points which could be improved. Soon I'll post a pulling request for your evaluation.

[[]]s
Fred

**Comment by fredericopissarra** [comment]
Where I can find your PGP public key... This is not working:

```
$ gpg --recv-keys 4AEE18F83AFDEB23
gpg: key 4AEE18F83AFDEB23: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```

Got this Key-ID from your signed commits.

**Comment by CoolerVoid** [comment]
Thank you, this is very cool.

My pub key https://raw.githubusercontent.com/CoolerVoid/C/master/CoolerVoid_pub.asc
I use this in e-mail context...

I gonna send to you a invite, to allow permissions in this repository.

**Comment by fredericopissarra** [comment]
Thanks for the invite... Already created changes-fred and test branches to avoid messing up with your code.
About the public key... It is interesing to upload to a keyserver so anyone can sign it and mark as any level of trusting. Anyway, I've imported here. Thanks.

Did some small changes on Makefile and match_algorithms.c. Take a look.
