### ISSUE TITLE
pcre.h: No such file or directory 

### ISSUE THREAD

**Issue by ShinTakata** [CoolerVoid/OctopusWAF#6]
How to solve this issue because i'm getting this error after i enter the command make.

make -C src
make[1]: Entering directory '/home/username/YourDirectoryName/OctopusWAF/src'
gcc -W -Wall -O2 -Wno-unused-variable -Wno-unused-parameter -fstack-protector-all -pie -fPIE -ftrapv -Iheaders   -c -o match_algorithms.o match_algorithms.c
In file included from match_algorithms.c:2:
headers/match_algorithms.h:10:10: fatal error: pcre.h: No such file or directory
   10 | #include <pcre.h>
      |          ^~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: match_algorithms.o] Error 1
make[1]: Leaving directory '/home/username/YourDirectoryName/OctopusWAF/src'
make: *** [Makefile:9: all] Error 2

**Comment by CoolerVoid** [comment]
You need install pcre library to run...
https://github.com/CoolerVoid/OctopusWAF#first-step

```
$ sudo apt-get install libpcre-dev
$ sudo apt-get install libpcre
```
